import type { ClassifiedPage, RouteGroup } from "./classify";
import type { PageForm } from "./crawl";

/**
 * Pick the strongest built-in expectation pack the page actually satisfied
 * during the crawl, so the generated preset passes on a healthy baseline and
 * only fails when something regresses. Returns null when nothing fits.
 */
export function packForFacts(page: ClassifiedPage): string | null {
  if (page.type === "home" && page.hasHeader && page.hasFooter)
    return "homepage";
  if (page.cardLinkCount >= 1) return "category";
  if (page.hasMain) return "has-main";
  if (page.h1) return "has-h1";
  if (page.hasHeader && page.hasFooter) return "static";
  return null;
}

/** Build the `urls-map.txt` preset body from the healthy route groups. */
export function buildPreset(groups: RouteGroup[], baseUrl: string): string {
  const lines: string[] = [
    "# urls-map.txt — generated by `web-tester map`.",
    "#",
    `# Source: ${baseUrl}`,
    "# One representative path per route template, annotated with the",
    "# strongest expectation pack the page satisfied when crawled. Review and",
    "# prune, then run:  web-tester sweep --preset map --fail-on http-5xx",
    ""
  ];
  for (const g of groups) {
    if (g.type === "error" || !g.representative.ok) continue;
    const pack = packForFacts(g.representative);
    const path = g.representative.finalPath || g.representative.path;
    const annotation = pack ? `  #pack=${pack}` : "";
    const note =
      g.count > 1 ? `   # ${g.count} pages share ${g.template}` : "";
    lines.push(`${path}${annotation}${note}`);
  }
  lines.push("");
  return lines.join("\n");
}

function kebab(s: string): string {
  return s
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

/** A draft value for a form field, by input type. */
function sampleValue(type: string): string | null {
  switch (type) {
    case "email":
      return "test@example.com";
    case "password":
      return "Password123!";
    case "tel":
      return "5551234567";
    case "number":
      return "1";
    case "url":
      return "https://example.com";
    case "search":
    case "text":
      return "test";
    case "textarea":
      return "Hello from web-tester";
    default:
      return null; // select / checkbox / radio / date etc. — skip
  }
}

/** Build fill/click steps for a form. Returns null if it can't be driven. */
function formSteps(form: PageForm): string[] | null {
  const steps: string[] = ["wait:networkidle"];
  let filled = 0;
  for (const field of form.fields) {
    if (!field.name) continue;
    const value = sampleValue(field.tag === "textarea" ? "textarea" : field.type);
    if (value === null) continue;
    // Quote the attribute value so names with special characters
    // (`user[email]`, `items[]`, dotted names) produce valid CSS.
    const tag =
      field.tag === "textarea"
        ? "textarea"
        : field.tag === "select"
          ? "select"
          : "input";
    const selector = `${tag}[name="${field.name}"]`;
    steps.push(`fill:${selector}=${value}`);
    filled++;
  }
  if (filled === 0) return null;
  steps.push("click:button[type=submit]");
  return steps;
}

export type DraftJourney = {
  name: string;
  journey: {
    description: string;
    url: string;
    steps: string[];
    expectations: string[];
    failOn: string;
  };
};

/**
 * Draft one journey per distinct form discovered. Forms are deduped by route
 * template + field signature so a form repeated across many pages yields a
 * single journey. These are starting points — values and expectations need a
 * human pass before they mean anything.
 */
export function buildJourneys(
  pages: ClassifiedPage[],
  limit: number
): DraftJourney[] {
  const seen = new Set<string>();
  const usedNames = new Set<string>();
  const drafts: DraftJourney[] = [];

  for (const page of pages) {
    if (!page.ok) continue;
    for (const form of page.forms) {
      const signature = `${page.template}::${form.fields
        .map((f) => `${f.name}:${f.tag}:${f.type}`)
        .sort()
        .join(",")}`;
      if (seen.has(signature)) continue;
      const steps = formSteps(form);
      if (!steps) continue;
      seen.add(signature);

      const path = page.finalPath || page.path;
      let base =
        page.type === "auth"
          ? /sign-?up|register/i.test(path)
            ? "signup"
            : "login"
          : kebab(path) || "form";
      base = `${base}-form`.replace(/-form-form$/, "-form");
      let name = base;
      let n = 2;
      while (usedNames.has(name)) name = `${base}-${n++}`;
      usedNames.add(name);

      drafts.push({
        name,
        journey: {
          description: `Auto-generated by \`web-tester map\` from the form on ${path}. Review the selectors, values, and add expectations before relying on it.`,
          url: path,
          steps,
          expectations: [],
          failOn: "http-5xx"
        }
      });
      if (drafts.length >= limit) return drafts;
    }
  }
  return drafts;
}

const RECIPES_START = "<!-- web-tester:map:start -->";
const RECIPES_END = "<!-- web-tester:map:end -->";

const TYPE_LABEL: Record<string, string> = {
  home: "Homepage",
  list: "List / index page",
  detail: "Detail page",
  form: "Form page",
  auth: "Auth page",
  search: "Search page",
  content: "Content page"
};

/** Build the marker-fenced "Generated by map" recipe section. */
export function buildRecipesSection(groups: RouteGroup[]): string {
  const lines: string[] = [
    RECIPES_START,
    "",
    "## Generated by `web-tester map`",
    "",
    "One smoke recipe per route template discovered. Re-running `web-tester map`",
    "refreshes this section. Promote the useful ones into the project-specific",
    "section above (they won't be overwritten there).",
    "",
    "### Sweep every discovered route",
    "",
    "```bash",
    "web-tester sweep --preset map --fail-on http-5xx",
    "```",
    ""
  ];

  for (const g of groups) {
    if (g.type === "error" || !g.representative.ok) continue;
    const path = g.representative.finalPath || g.representative.path;
    const pack = packForFacts(g.representative);
    const expects: string[] = [];
    if (pack === "homepage" || pack === "static") {
      expects.push("--expect \"selector=header\"", "--expect \"selector=footer\"");
    } else if (pack === "category") {
      expects.push(
        "--expect \"selector=main\"",
        "--expect \"selector=main a[href^='/']:has(img)\""
      );
    } else if (pack === "has-main") {
      expects.push("--expect \"selector=main\"");
    } else if (pack === "has-h1") {
      expects.push("--expect \"selector=h1\"");
    }
    const label = TYPE_LABEL[g.type] ?? "Page";
    const cmd = [
      `web-tester inspect "${path}" \\`,
      "  --step wait:networkidle --quick \\",
      ...expects.map((e) => `  ${e} \\`),
      "  --fail-on http-5xx"
    ].join("\n");
    lines.push(
      `### ${label} — \`${g.template}\``,
      "",
      `**When:** verifying \`${g.template}\` still renders.`,
      "",
      "```bash",
      cmd,
      "```",
      ""
    );
  }

  lines.push(RECIPES_END);
  return lines.join("\n");
}

/**
 * Merge the generated recipe section into an existing recipes.md body,
 * replacing a previous generated block if present. Returns the full file.
 */
export function mergeRecipes(existing: string | null, section: string): string {
  if (!existing) {
    return `# Recipes\n\nCopy-paste one-liners for common web-tester runs.\n\n${section}\n`;
  }
  const start = existing.indexOf(RECIPES_START);
  const end = existing.indexOf(RECIPES_END);
  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + RECIPES_END.length);
    return `${before}${section}${after}`;
  }
  const sep = existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing}${sep}${section}\n`;
}
